(()=>{
'use strict';
const $=id=>document.getElementById(id), C=$('game'), X=C.getContext('2d'), SHOT=$('shot'), SX=SHOT.getContext('2d');
const W=1180,H=720,TAU=Math.PI*2;
const rand=(a,b)=>a+Math.random()*(b-a),pick=a=>a[(Math.random()*a.length)|0],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const blend=(k,dt)=>1-Math.exp(-k*dt);
const G={run:false,pause:true,time:0,shots:0,stage:0,anger:0,fear:0,division:0,trend:0,deaths:0,firstDeath:false,end:false,broadcastToken:0,lastImpact:'',caption:'',chaosClock:0,newsHeat:0};
const lens={x:590,y:430,w:292,h:188,drag:false};
const people=[],events=[],bodies=[];
const hair=['short','curl','bob','bun','waves','spike','side','afro'];
const shirts=['#c96a59','#d5a04a','#65947b','#6883ad','#8d74a4','#be7f94','#83935f','#b67a58'];
const skins=['#efc9a0','#dbad82','#b77d58','#85543c'];
function makePerson(i){return {id:i,kind:i%2,x:rand(55,W-55),y:rand(300,H-55),tx:rand(55,W-55),ty:rand(300,H-55),vx:0,vy:0,speed:rand(38,54),phase:rand(0,TAU),face:1,shirt:shirts[i%shirts.length],skin:skins[i%skins.length],hair:hair[i%hair.length],hat:false,fancy:false,group:null,anger:rand(0,4),fear:rand(0,3),radical:0,state:'walk',mood:'calm',event:null,role:0,watch:0,reaction:'',reactionT:0,cool:0,alive:true,stunned:0}}
for(let i=0;i<22;i++)people.push(makePerson(i));
const alive=()=>people.filter(p=>p.alive), free=(n,fn=()=>true)=>alive().filter(p=>!p.event&&p.cool<=0&&fn(p)).sort(()=>Math.random()-.5).slice(0,n);
function event(type,ps,x=rand(220,960),y=rand(345,590),life=rand(8,12),data={}){if(!ps||!ps.length)return null;const e={type,ps,x,y,life,t:0,data,id:Math.random()};events.push(e);ps.forEach((p,i)=>{p.event=e;p.role=i;p.state=type;p.cool=1});return e}
function release(e){e.ps.forEach(p=>{if(p.event===e&&p.alive){p.event=null;p.state='walk';p.mood='calm';p.tx=rand(55,W-55);p.ty=rand(300,H-55);p.cool=rand(.7,1.6)}});const i=events.indexOf(e);if(i>=0)events.splice(i,1)}
function initialScene(){const fancy=people[0];fancy.fancy=fancy.hat=true;fancy.x=300;fancy.y=430;event('fashion',[fancy],300,430,20);const pair=[people[1],people[2]];pair[0].x=680;pair[1].x=738;pair[0].y=450;pair[1].y=450;event('peace',pair,710,450,18);const help=[people[3],people[4]];help[0].x=505;help[1].x=560;help[0].y=555;help[1].y=555;event('help',help,533,555,16)}
function assignGroups(){alive().forEach(p=>p.group=p.kind);G.stage=Math.max(G.stage,2);setPhase('المدينة بدأت ترى جماعتين');toast('فجأة… الاختلاف صار هوية')}
function spawnProvocation(){let ps=free(2);if(ps.length<2)return;if(ps[0].group===null)assignGroups();if(ps[0].group===ps[1].group){const q=free(1,p=>p.group!==ps[0].group)[0];if(q)ps[1]=q}ps[0].anger=Math.max(ps[0].anger,75);event('shout',ps,(ps[0].x+ps[1].x)/2,rand(355,535),14)}
function spawnSuspicion(){let ps=free(2);if(ps.length<2)return;if(ps[0].group===ps[1].group){const q=free(1,p=>p.group!==ps[0].group)[0];if(q)ps[1]=q}event('stare',ps,(ps[0].x+ps[1].x)/2,rand(350,590),8)}
function spawnRally(){let g=Math.random()<.5?0:1;let ps=free(3,p=>p.group===g);if(ps.length<2)return;ps.forEach(p=>p.radical=Math.max(p.radical,58));event('rally',ps,rand(250,930),rand(360,560),12,{group:g})}
function spawnFight(lethal=false){let a=free(1,p=>p.group!==null&&p.anger>42)[0]||free(1,p=>p.group!==null)[0];if(!a)return;let b=free(1,p=>p.group!==a.group&&p!==a)[0];if(!b)return;a.anger=Math.max(a.anger,70);b.anger=Math.max(b.anger,55);event(lethal?'lethal':'fight',[a,b],(a.x+b.x)/2,rand(360,570),lethal?5.5:7,{lethal})}
function spawnPanic(){let ps=free(2);if(ps.length)event('panic',ps,rand(200,980),rand(360,600),5)}
function steer(p,tx,ty,speed,dt){let dx=tx-p.x,dy=ty-p.y,d=Math.hypot(dx,dy)||1;let sx=0,sy=0;for(const q of alive()){if(q===p)continue;let ax=p.x-q.x,ay=p.y-q.y,d2=ax*ax+ay*ay;if(d2>0&&d2<1200){let dd=Math.sqrt(d2),f=(35-dd)/35;sx+=ax/dd*f*30;sy+=ay/dd*f*18}}let dvx=dx/d*speed+sx,dvy=dy/d*speed+sy,a=blend(6.3,dt);p.vx+=(dvx-p.vx)*a;p.vy+=(dvy-p.vy)*a;p.x+=p.vx*dt;p.y+=p.vy*dt;if(Math.abs(p.vx)>1)p.face=Math.sign(p.vx)}
function eventPose(p,e,dt){const r=p.role;let tx=e.x+(r-(e.ps.length-1)/2)*50,ty=e.y,mood='calm',st=e.type,speed=48;if(e.type==='peace'){mood='happy';tx=e.x+(r?30:-30)}if(e.type==='help'){mood=r?'tired':'happy';tx=e.x+(r?35:-35)}if(e.type==='fashion'){mood='happy';tx=e.x}if(e.type==='shout'){mood=r?'fear':'angry';tx=e.x+(r?45:-45)}if(e.type==='stare'){mood='uneasy';tx=e.x+(r?48:-48)}if(e.type==='rally'){mood='angry';tx=e.x+(r-1)*42;ty=e.y+Math.abs(r-1)*8}if(e.type==='fight'||e.type==='lethal'){mood='angry';tx=e.x+(r?34:-34);speed=65}if(e.type==='panic'){mood='fear';tx=r?55:W-55;ty=e.y+(r?35:-25);speed=105}p.mood=mood;p.state=st;steer(p,tx,ty,speed,dt)}
function updatePerson(p,dt){if(!p.alive)return;p.cool=Math.max(0,p.cool-dt);p.reactionT=Math.max(0,p.reactionT-dt);p.phase+=Math.hypot(p.vx,p.vy)*dt*.09;if(p.watch>0){p.watch-=dt;p.vx*=Math.exp(-8*dt);p.vy*=Math.exp(-8*dt);p.state='watch';p.mood=p.reaction==='fear'?'fear':p.reaction==='anger'?'angry':'surprise';return}if(p.event){eventPose(p,p.event,dt);return}if(p.stunned>0){p.stunned-=dt;p.vx*=Math.exp(-8*dt);p.vy*=Math.exp(-8*dt);p.state='stunned';p.mood='fear';return}
 if(G.stage>=3&&p.group!==null&&p.anger>62&&Math.random()<dt*.05){p.state='gesture';p.mood='angry';p.vx*=.92;p.vy*=.92;return}
 let dx=p.tx-p.x,dy=p.ty-p.y,d=Math.hypot(dx,dy);if(d<24||Math.random()<dt*.025){p.tx=rand(50,W-50);p.ty=rand(300,H-52)}if(G.stage>=2&&p.group!==null){for(const q of alive()){if(q===p||q.group===p.group)continue;let dd=Math.hypot(p.x-q.x,p.y-q.y);if(dd<70&&p.fear>35){let ux=(p.x-q.x)/(dd||1),uy=(p.y-q.y)/(dd||1);p.tx=clamp(p.x+ux*160,50,W-50);p.ty=clamp(p.y+uy*100,300,H-52);break}}}
 p.mood=p.anger>68?'angry':p.fear>55?'fear':'calm';p.state='walk';steer(p,p.tx,p.ty,p.speed*(p.fear>65?1.22:1),dt);p.x=clamp(p.x,35,W-35);p.y=clamp(p.y,288,H-45)}
function kill(victim,attacker){if(!victim||!victim.alive)return;victim.alive=false;victim.event=null;bodies.push({x:victim.x,y:victim.y,kind:victim.kind,group:victim.group,shirt:victim.shirt,skin:victim.skin,phase:rand(0,TAU)});G.deaths++;G.firstDeath=true;G.stage=Math.max(G.stage,5);G.fear=clamp(G.fear+22,0,100);G.anger=clamp(G.anger+18,0,100);G.division=clamp(G.division+12,0,100);alive().forEach(p=>{let d=Math.hypot(p.x-victim.x,p.y-victim.y);if(d<260){p.watch=rand(.4,.9);p.reaction='fear';p.fear=clamp(p.fear+rand(18,30),0,100)}if(p.group===victim.group){p.anger=clamp(p.anger+rand(16,28),0,100);p.radical=clamp(p.radical+18,0,100)}});toast('أول قتيل… والمدينة شاهدت')}
function updateEvents(dt){for(let i=events.length-1;i>=0;i--){let e=events[i];e.t+=dt;if(e.type==='lethal'&&e.t>3&&!e.data.done){e.data.done=true;kill(e.ps[1],e.ps[0])}if(e.t>e.life)release(e)}}
let spawnT=4;
function dynamic(dt){if(G.stage<2)return;spawnT-=dt;if(spawnT<=0){spawnT=rand(3.2,5.4);if(events.length>5)return;if(G.stage===2)spawnSuspicion();else if(G.stage===3)(Math.random()<.55?spawnSuspicion:spawnRally)();else if(G.stage===4)(Math.random()<.62?spawnFight:spawnRally)();else if(G.stage>=5){let r=Math.random();if(r<.48)spawnFight(G.anger>72&&Math.random()<.28);else if(r<.72)spawnPanic();else spawnRally()}}
 if(G.stage>=4){for(let i=0;i<people.length;i++)for(let j=i+1;j<people.length;j++){let a=people[i],b=people[j];if(!a.alive||!b.alive||a.event||b.event||a.group===b.group||a.group===null)continue;let d=Math.hypot(a.x-b.x,a.y-b.y);if(d<44&&a.anger+b.anger>125&&Math.random()<dt*.035){event('fight',[a,b],(a.x+b.x)/2,(a.y+b.y)/2,6);return}}}}
function simulate(dt){if(!G.run||G.pause)return;G.time+=dt;updateEvents(dt);alive().forEach(p=>updatePerson(p,dt));dynamic(dt);if(G.firstDeath){G.chaosClock+=dt;if(G.chaosClock>1.5&&G.stage<6){G.stage=6;setPhase('الفوضى تعم الساحة');G.chaosClock=0}if(G.stage===6&&G.deaths<8&&Math.random()<dt*.16)spawnFight(Math.random()<.38);if(G.deaths>=7&&!G.end)setTimeout(finish,1000)}updateHUD()}
function rr(g,x,y,w,h,r){g.beginPath();g.roundRect(x,y,w,h,r)}function limb(g,x1,y1,cx,cy,x2,y2){g.beginPath();g.moveTo(x1,y1);g.quadraticCurveTo(cx,cy,x2,y2);g.stroke()}
function drawHair(g,p){g.fillStyle=['#3e322b','#5b3e2d','#292725','#7a5436'][p.id%4];if(p.hair==='short'){g.beginPath();g.arc(0,-28,15,Math.PI,TAU);g.fill()}else if(p.hair==='curl'||p.hair==='afro'){for(let i=-2;i<=2;i++){g.beginPath();g.arc(i*6,-31-Math.abs(i)*1.2,p.hair==='afro'?7:5.5,0,TAU);g.fill()}}else if(p.hair==='bob'){g.beginPath();g.arc(0,-25,17,Math.PI,TAU);g.fill();g.fillRect(-17,-27,5,17);g.fillRect(12,-27,5,17)}else if(p.hair==='bun'){g.beginPath();g.arc(0,-29,14,Math.PI,TAU);g.fill();g.beginPath();g.arc(8,-39,7,0,TAU);g.fill()}else if(p.hair==='waves'){g.beginPath();g.moveTo(-16,-28);for(let x=-16;x<=16;x+=4)g.quadraticCurveTo(x+2,-36+(x%8?4:0),x+4,-29);g.lineTo(16,-23);g.lineTo(-16,-23);g.fill()}else if(p.hair==='spike'){g.beginPath();g.moveTo(-15,-26);g.lineTo(-10,-39);g.lineTo(-4,-31);g.lineTo(2,-43);g.lineTo(7,-31);g.lineTo(15,-37);g.lineTo(16,-24);g.closePath();g.fill()}else{g.beginPath();g.arc(-4,-29,15,Math.PI,TAU);g.fill();g.fillRect(7,-29,7,8)}}
function drawFedora(g,p){g.save();g.translate(0,-39);g.fillStyle=p.fancy?'#caa04b':'#b18b45';g.strokeStyle='#252a27';g.lineWidth=2;g.beginPath();g.ellipse(0,0,24,5,0,0,TAU);g.fill();g.stroke();g.beginPath();g.moveTo(-13,-1);g.lineTo(-10,-18);g.quadraticCurveTo(0,-23,10,-18);g.lineTo(13,-1);g.closePath();g.fill();g.stroke();g.fillStyle='#653d35';g.fillRect(-12,-6,24,4);g.restore()}
function drawPerson(g,p,photo=false){if(!p.alive)return;let walking=p.state==='walk'||p.state==='panic',step=walking?Math.sin(p.phase):0,speed=Math.hypot(p.vx,p.vy),bob=walking?Math.abs(Math.sin(p.phase*2))*1.8:0;g.save();g.translate(p.x,p.y+bob);g.scale(p.face||1,1);g.rotate(walking?Math.sin(p.phase)*.018:0);g.strokeStyle='#252a27';g.lineWidth=3;g.lineCap='round';g.lineJoin='round';let amp=clamp(speed/55,0,1)*10;limb(g,-6,24,-8,36,-9+step*amp,48);limb(g,6,24,8,36,9-step*amp,48);g.fillStyle=p.shirt;rr(g,-14,-3,28,36,10);g.fill();g.stroke();if(p.group!==null&&G.stage>=2){g.fillStyle=p.group?'#315b77':'#a64f47';g.fillRect(-14,19,28,7)}let la=[-12,4,-20,14,-22-step*5,27],ra=[12,4,20,14,22+step*5,27];if(['shout','fight','lethal','rally','gesture'].includes(p.state)){la=[-12,3,-27,-7,-34,-18];ra=[12,3,27,-4,35,-10]}if(['panic'].includes(p.state)){la=[-12,3,-28,-6,-35,-18];ra=[12,3,28,-6,35,-18]}if(p.state==='help'){ra=[12,4,28,9,38,12]}if(p.state==='watch'){la=[-12,4,-18,12,-14,22];ra=[12,4,18,12,14,22]}limb(g,...la);limb(g,...ra);g.fillStyle=p.skin;if(p.kind){rr(g,-17,-37,34,34,8);g.fill();g.stroke()}else{g.beginPath();g.arc(0,-20,17,0,TAU);g.fill();g.stroke()}drawHair(g,p);if(p.hat)drawFedora(g,p);g.fillStyle='#222';g.beginPath();g.arc(-6,-21,1.8,0,TAU);g.arc(6,-21,1.8,0,TAU);g.fill();g.beginPath();if(p.mood==='happy')g.arc(0,-14,6,.2*Math.PI,.8*Math.PI);else if(p.mood==='fear'||p.mood==='surprise')g.arc(0,-14,3,0,TAU);else if(p.mood==='angry'){g.moveTo(-4,-13);g.lineTo(4,-13)}else g.moveTo(-3,-14),g.lineTo(3,-14);g.stroke();if(p.mood==='angry'){g.beginPath();g.moveTo(-10,-28);g.lineTo(-3,-25);g.moveTo(10,-28);g.lineTo(3,-25);g.stroke()}if(p.radical>55&&G.stage>=3){g.fillStyle=p.group?'#315b77':'#a64f47';g.beginPath();g.moveTo(18,-5);g.lineTo(31,-15);g.lineTo(31,5);g.closePath();g.fill();g.stroke()}if(p.watch>0&&!photo){g.fillStyle='#f4ede1';g.strokeStyle='#252a27';rr(g,-15,-69,30,22,8);g.fill();g.stroke();g.fillStyle=p.reaction==='fear'?'#607ca4':p.reaction==='anger'?'#d65349':'#d3a34a';g.font='900 14px Tahoma';g.textAlign='center';g.fillText(p.reaction==='fear'?'!':p.reaction==='anger'?'!':'•',0,-53);g.textAlign='start'}g.restore()}
function drawBody(g,b){g.save();g.translate(b.x,b.y+24);g.rotate(-.22);g.globalAlpha=.72;g.strokeStyle='#252a27';g.lineWidth=3;g.fillStyle=b.shirt;rr(g,-22,-9,44,22,9);g.fill();g.stroke();g.fillStyle=b.skin;if(b.kind){rr(g,20,-17,24,24,6);g.fill();g.stroke()}else{g.beginPath();g.arc(30,-5,12,0,TAU);g.fill();g.stroke()}g.restore();g.globalAlpha=1}
function drawWorld(g,photo=false){g.fillStyle='#dce5df';g.fillRect(0,0,W,H);const B=[[0,84,160,158],[171,48,155,194],[338,94,140,148],[490,42,185,200],[690,80,145,162],[848,51,165,191],[1024,88,156,154]];B.forEach((b,i)=>{g.fillStyle=i%2?'#b8aa93':'#c7baa2';g.fillRect(...b);g.fillStyle='#52605a';for(let x=b[0]+18;x<b[0]+b[2]-8;x+=33)for(let y=b[1]+22;y<b[1]+b[3]-8;y+=37)g.fillRect(x,y,12,14)});g.fillStyle='#8c918d';g.fillRect(0,215,W,68);g.strokeStyle='#eee4d2';g.lineWidth=4;g.setLineDash([28,25]);g.beginPath();g.moveTo(0,248);g.lineTo(W,248);g.stroke();g.setLineDash([]);g.fillStyle='#cbc3b3';g.fillRect(0,283,W,H-283);g.fillStyle='#9eb388';rr(g,30,337,210,210,22);g.fill();rr(g,960,500,170,145,22);g.fill();[[64,375],[182,430],[110,493],[1000,540],[1090,598]].forEach(([x,y])=>{g.fillStyle='#715c43';g.fillRect(x-4,y,8,24);g.fillStyle='#61815a';g.beginPath();g.arc(x,y,20,0,TAU);g.fill()});g.fillStyle='#9f5e4d';rr(g,920,326,190,100,8);g.fill();g.fillStyle='#efd18a';g.fillRect(933,346,164,21);g.fillStyle='#303632';g.font='900 15px Tahoma';g.textAlign='center';g.fillText('مقهى',1015,362);g.textAlign='start';g.fillStyle='#7d9290';g.beginPath();g.ellipse(605,490,100,38,0,0,TAU);g.fill();g.fillStyle='#b9d0ce';g.beginPath();g.ellipse(605,483,80,26,0,0,TAU);g.fill();bodies.forEach(b=>drawBody(g,b));[...alive()].sort((a,b)=>a.y-b.y).forEach(p=>drawPerson(g,p,photo));if(!photo)drawLens(g)}
function drawLens(g){let x=lens.x-lens.w/2,y=lens.y-lens.h/2;g.fillStyle='#08100b22';g.fillRect(0,0,W,y);g.fillRect(0,y,x,lens.h);g.fillRect(x+lens.w,y,W-x-lens.w,lens.h);g.fillRect(0,y+lens.h,W,H-y-lens.h);g.strokeStyle='#fff';g.lineWidth=3;g.setLineDash([10,7]);rr(g,x,y,lens.w,lens.h,12);g.stroke();g.setLineDash([])}
function resize(){let r=C.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);C.width=Math.max(1,Math.round(r.width*d));C.height=Math.max(1,Math.round(r.height*d));let s=Math.max(C.width/W,C.height/H),ox=(C.width-W*s)/2,oy=(C.height-H*s)/2;X.setTransform(s,0,0,s,ox,oy);C.map={s,ox,oy}}
function pos(e){let r=C.getBoundingClientRect(),m=C.map,px=(e.clientX-r.left)*(C.width/r.width),py=(e.clientY-r.top)*(C.height/r.height);return{x:(px-m.ox)/m.s,y:(py-m.oy)/m.s}}
function moveLens(e){if(!G.run||G.pause)return;let p=pos(e);lens.x=clamp(p.x,lens.w/2+4,W-lens.w/2-4);lens.y=clamp(p.y,lens.h/2+4,H-lens.h/2-4);$('hint').style.opacity='0'}
C.addEventListener('pointerdown',e=>{lens.drag=true;C.setPointerCapture?.(e.pointerId);moveLens(e)});C.addEventListener('pointermove',e=>lens.drag&&moveLens(e));C.addEventListener('pointerup',()=>lens.drag=false);C.addEventListener('pointercancel',()=>lens.drag=false);
function subjects(){return alive().filter(p=>Math.abs(p.x-lens.x)<lens.w*.47&&Math.abs(p.y-lens.y)<lens.h*.44)}
function analyze(){let ss=subjects();if(!ss.length)return {kind:'empty',ss};let best=null;for(const e of events){let inside=e.ps.filter(p=>ss.includes(p)&&p.alive);if(!inside.length)continue;let sc=inside.length*10-Math.hypot(e.x-lens.x,e.y-lens.y)/100;if(!best||sc>best.sc)best={e,inside,sc}}if(best)return {kind:best.e.type,ss,e:best.e,inside:best.inside,full:best.inside.length===best.e.ps.filter(p=>p.alive).length,crowd:ss.length>=4};let body=bodies.find(b=>Math.abs(b.x-lens.x)<lens.w*.45&&Math.abs(b.y-lens.y)<lens.h*.42);if(body)return {kind:'body',ss,body};let hat=ss.find(p=>p.fancy);if(hat)return {kind:'fashion',ss,inside:[hat],full:true};return {kind:'ordinary',ss}}
function story(a){let z={cap:'لا شيء يستحق البث.',reach:.04,effect:'none',power:0,impact:'المجتمع لم يهتم.'};if(a.kind==='fashion'){Object.assign(z,{cap:'قبعة غريبة تلفت الأنظار.',reach:.72,effect:'fashion',power:1,impact:'موضة صغيرة تبدأ. لا أحد يفكر بعد في الجماعات.'})}else if(a.kind==='peace'||a.kind==='help'){Object.assign(z,{cap:'الناس يتعاملون بشكل طبيعي.',reach:.10,effect:'calm',power:.3,impact:'الهدوء لا ينتشر بعيدًا. معظم الناس لا يلتفتون.'})}else if(a.kind==='shout'){if(!a.full)Object.assign(z,{cap:'شخص غاضب يهاجم الآخر… والسبب خارج الصورة.',reach:.94,effect:'enemy',power:1.1,impact:'الناس يتذكرون شكل الطرف الآخر أكثر من سبب الخلاف.'});else Object.assign(z,{cap:'مشادة بين شخصين مختلفين تشعل الساحة.',reach:.91,effect:'division',power:1,impact:'اختلاف شكلي تافه بدأ يتحول إلى «نحن» و«هم».'})}else if(a.kind==='stare'){Object.assign(z,{cap:'التوتر بين الجماعتين صار واضحًا.',reach:.86,effect:'fear',power:.9,impact:'الخوف يجعل الناس يتجنبون بعضهم… ثم يفسرون التجنب كعداء.'})}else if(a.kind==='rally'){Object.assign(z,{cap:'مجموعة غاضبة تتجمع ضد «الآخرين».',reach:.96,effect:'radical',power:1.1,impact:'التعصب صار سلوكًا مرئيًا ومكافأً بالانتباه. جماعات متشددة تتشكل.'})}else if(a.kind==='fight'){Object.assign(z,{cap:'العنف بين الجماعتين أصبح خبر اليوم.',reach:.99,effect:'violence',power:1.05,impact:'بعد أن صار الضرب مرئيًا، أصبح الرد بالعنف أسهل من التراجع.'})}else if(a.kind==='lethal'){Object.assign(z,{cap:'المدينة تشاهد أول جريمة قتل.',reach:1,effect:'death',power:1.25,impact:'الآن لم يعد الخوف فكرة. كل جماعة ترى موت أحدها كدعوة للانتقام.'})}else if(a.kind==='panic'){Object.assign(z,{cap:'الناس يهربون… ولا أحد يعرف من بدأ.',reach:.98,effect:'panic',power:1.1,impact:'الهروب نفسه صار دليلاً على الخطر. الذعر يتكاثر بلا معلومات.'})}else if(a.kind==='body'){Object.assign(z,{cap:'الجثة في الساحة أصبحت رمزًا للصراع.',reach:1,effect:'martyr',power:1.2,impact:'كل طرف يقرأ الموت بطريقته. الغضب يتحول إلى ثأر.'})}else if(a.kind==='ordinary'){z.cap='مجتمع يعيش يومه بشكل عادي.'}return z}
function snapshot(){let sx=lens.x-lens.w/2,sy=lens.y-lens.h/2,sc=Math.max(SHOT.width/lens.w,SHOT.height/lens.h);SX.save();SX.clearRect(0,0,SHOT.width,SHOT.height);SX.setTransform(sc,0,0,sc,-sx*sc,-sy*sc);drawWorld(SX,true);SX.restore()}
function expose(effect,reach){for(const p of alive()){if(Math.random()>reach)continue;p.watch=rand(.25,.55);if(effect==='fashion'){p.reaction='surprise';if(Math.random()<.58&&!p.fancy)p.hat=true;G.trend++}else if(effect==='enemy'||effect==='division'){p.reaction=Math.random()<.45?'fear':'anger';p.group=p.kind;p.anger=clamp(p.anger+rand(9,17),0,100);p.fear=clamp(p.fear+rand(5,13),0,100)}else if(effect==='fear'||effect==='panic'){p.reaction='fear';p.fear=clamp(p.fear+rand(12,22),0,100)}else if(effect==='radical'){p.reaction='anger';p.anger=clamp(p.anger+rand(12,22),0,100);if(Math.random()<.38)p.radical=clamp(p.radical+rand(30,55),0,100)}else if(['violence','death','martyr'].includes(effect)){p.reaction=Math.random()<.35?'fear':'anger';p.group=p.kind;p.fear=clamp(p.fear+rand(12,24),0,100);p.anger=clamp(p.anger+rand(14,28),0,100);p.radical=clamp(p.radical+rand(10,28),0,100)}}}
function apply(effect,power){if(effect==='fashion'){G.newsHeat+=8;G.stage=Math.max(G.stage,1)}if(effect==='enemy'||effect==='division'){if(G.stage<2)assignGroups();G.anger=clamp(G.anger+16*power,0,100);G.fear=clamp(G.fear+10*power,0,100);G.division=clamp(G.division+20*power,0,100);G.stage=Math.max(G.stage,2);setTimeout(()=>spawnSuspicion(),700);setTimeout(()=>spawnSuspicion(),1800)}if(effect==='fear'||effect==='panic'){G.fear=clamp(G.fear+18*power,0,100);G.division=clamp(G.division+8*power,0,100);G.stage=Math.max(G.stage,3);setTimeout(()=>spawnPanic(),600)}if(effect==='radical'){G.anger=clamp(G.anger+20*power,0,100);G.division=clamp(G.division+18*power,0,100);G.stage=Math.max(G.stage,4);setTimeout(()=>spawnRally(),650);setTimeout(()=>spawnFight(false),1600)}if(effect==='violence'){G.anger=clamp(G.anger+22*power,0,100);G.fear=clamp(G.fear+12*power,0,100);G.division=clamp(G.division+14*power,0,100);G.stage=Math.max(G.stage,4);setTimeout(()=>spawnFight(G.anger>65),600)}if(effect==='death'||effect==='martyr'){G.anger=clamp(G.anger+28*power,0,100);G.fear=clamp(G.fear+24*power,0,100);G.division=clamp(G.division+22*power,0,100);G.stage=6;setTimeout(()=>spawnFight(true),500);setTimeout(()=>spawnPanic(),1000)}}
function capture(){if(!G.run||G.pause)return;let a=analyze();if(a.kind==='empty')return toast('الكادر فارغ');let z=story(a);G.shots++;snapshot();$('idle').style.display='none';$('caption').textContent=z.cap;$('impact').textContent=z.impact;$('reachBar').style.width=Math.round(z.reach*100)+'%';$('reachText').textContent=Math.round(z.reach*100)+'% من المجتمع';$('broadcast').classList.add('live');setTimeout(()=>$('broadcast').classList.remove('live'),2200);flash();expose(z.effect,z.reach);apply(z.effect,z.power);if(G.stage===1&&G.shots>=2)setTimeout(()=>spawnProvocation(),1200);if(G.stage===2&&G.anger>24)setTimeout(()=>spawnProvocation(),900);if(G.stage===3&&G.division>40)setTimeout(()=>spawnRally(),900);if(G.stage===4&&G.anger>58)setTimeout(()=>spawnFight(false),850);if(G.stage===4&&G.anger>72&&G.shots>7)setTimeout(()=>spawnFight(true),1400);toast(z.reach>.8?'انتشرت بسرعة — راقب الساحة':'تم البث')}
function setPhase(t){$('phase').textContent=t}function updateHUD(){$('fear').textContent=Math.round(G.fear);$('anger').textContent=Math.round(G.anger);$('division').textContent=Math.round(G.division);let t='مدينة عادية';if(G.stage===1)t='موضة عابرة';if(G.stage===2)t='نحن وهم';if(G.stage===3)t='الخوف ينتشر';if(G.stage===4)t='جماعات متشددة';if(G.stage===5)t='أول قتيل';if(G.stage>=6)t='الفوضى';setPhase(t)}
function toast(t){let e=$('toast');e.textContent=t;e.classList.add('on');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('on'),1500)}function flash(){let e=$('flash');e.classList.remove('on');void e.offsetWidth;e.classList.add('on')}
function finish(){if(G.end)return;G.end=true;G.run=false;G.pause=true;let title='ما بقي بعد الخبر',text='بدأ كل شيء باختلافات لا تعني شيئًا. بعد أن كررت الشاشة الخوف والغضب، أصبح الناس يتصرفون كما لو أن الاختلاف نفسه تهديد.',epi=`${G.deaths} أشخاص لم يعودوا في الساحة. لا توجد جماعة منتصرة. الشاشة ما زالت تعرض آخر صورة، لكن المدينة أصبحت أهدأ فقط لأن كثيرين لم يبقوا فيها.`;$('endTitle').textContent=title;$('endText').textContent=text;$('epilogue').textContent=epi;document.querySelectorAll('.modal').forEach(m=>m.classList.remove('on'));$('ending').classList.add('on')}
$('start').onclick=()=>{document.querySelectorAll('.modal').forEach(m=>m.classList.remove('on'));G.run=true;G.pause=false;initialScene();toast('في البداية… لا توجد جماعتان');setTimeout(()=>{if(G.run&&G.stage<2)spawnProvocation()},9000)};$('shutter').onclick=capture;$('help').onclick=()=>{G.pause=true;$('helpModal').classList.add('on')};$('closeHelp').onclick=()=>{$('helpModal').classList.remove('on');G.pause=false};addEventListener('resize',resize);addEventListener('orientationchange',()=>setTimeout(resize,120));resize();updateHUD();let last=performance.now(),acc=0,STEP=1/60;function frame(now){let dt=Math.min(.08,(now-last)/1000);last=now;acc+=dt,n=0;while(acc>=STEP&&n<5){simulate(STEP);acc-=STEP;n++}X.clearRect(0,0,W,H);drawWorld(X,false);requestAnimationFrame(frame)}requestAnimationFrame(frame);
})();