(()=>{
'use strict';
const $=id=>document.getElementById(id);
const C=$('game'),X=C.getContext('2d'),SHOT=$('shot'),SX=SHOT.getContext('2d');
const W=1040,H=720,TAU=Math.PI*2;
const rand=(a,b)=>a+Math.random()*(b-a), pick=a=>a[(Math.random()*a.length)|0], clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const expBlend=(rate,dt)=>1-Math.exp(-rate*dt);
const G={run:false,pause:true,shots:0,time:0,phase:0,anger:5,fear:4,vanity:3,trust:72,division:2,hatTrend:0,hatBored:0,broadcast:null,broadcastToken:0,lastCaption:'',end:false,interesting:0};
const lens={x:530,y:420,w:292,h:184,drag:false,moved:false,downX:0,downY:0};
const names='سلمى عمر ليان مالك نور آدم مريم يونس رهف سامي آية كريم لينا أنس هبة زياد جود ريان سارة علي ريم مازن هالة إياد دانا باسل رنا نوح لمى فارس تالا يزن'.split(' ');
const colors=['#d86b5d','#d6a04a','#64977e','#6684b1','#8b73a6','#bf7f97','#83935f','#b97854'];
const skins=['#efcda7','#d8aa7f','#ac7551','#7e5038'];
const P=[],E=[];
let featuredHat=null, featuredShouter=null;
function makePerson(i){return {id:i,name:names[i%names.length],group:i%2,x:rand(55,W-55),y:rand(305,H-58),tx:rand(55,W-55),ty:rand(305,H-58),vx:0,vy:0,speed:rand(34,52),color:colors[i%colors.length],skin:skins[i%skins.length],phase:rand(0,TAU),face:1,state:'walk',mood:'calm',event:null,role:0,hat:false,fancyHat:false,anger:rand(0,6),fear:rand(0,5),vanity:rand(0,6),empathy:rand(25,70),fame:0,watchT:0,actionT:0,action:'',reaction:'',reactionT:0,seenToken:0,cooldown:rand(0,2),featured:''}}
for(let i=0;i<32;i++)P.push(makePerson(i));
function freePeople(n,filter=()=>true){return P.filter(p=>!p.event&&p.watchT<=0&&filter(p)).sort(()=>Math.random()-.5).slice(0,n)}
function oppositePair(){let a=freePeople(1)[0];if(!a)return null;let b=freePeople(1,p=>p!==a&&p.group!==a.group)[0];return b?[a,b]:null}
function createEvent(type,people,x=rand(245,870),y=rand(350,570),life=rand(9,13)){if(!people||!people.length)return null;const e={type,people,x,y,life,t:0,id:Math.random()};E.push(e);people.forEach((p,i)=>{p.event=e;p.role=i;p.state=type;p.cooldown=1.5});return e}
function spawnEvent(type){if(E.length>5)return null;let ps=null;if(type==='hat')ps=freePeople(1);else if(type==='friends')ps=oppositePair();else if(type==='fight')ps=oppositePair();else if(type==='help'||type==='prank'||type==='panic')ps=freePeople(2);else if(type==='pose')ps=freePeople(1,p=>p.vanity>35||p.fame>20);if(!ps||!ps.length)return null;return createEvent(type,ps)}
function releaseEvent(e){if(!e)return;e.people.forEach(p=>{if(p.event===e){p.event=null;p.state='walk';p.mood='calm';p.action='';p.tx=rand(55,W-55);p.ty=rand(305,H-58);p.cooldown=rand(.5,1.5)}});const i=E.indexOf(e);if(i>=0)E.splice(i,1)}
function spawnInitial(){featuredHat=P[0];featuredHat.featured='hat';featuredHat.fancyHat=true;featuredHat.hat=true;featuredHat.x=350;featuredHat.y=425;featuredHat.tx=350;featuredHat.ty=425;createEvent('hat',[featuredHat],350,425,18);const pair=[P[1],P[2]];pair[0].group=0;pair[1].group=1;pair[0].x=680;pair[1].x=735;pair[0].y=445;pair[1].y=445;createEvent('friends',pair,707,445,17);const help=[P[3],P[4]];help[0].x=520;help[1].x=575;help[0].y=560;help[1].y=560;createEvent('help',help,548,560,16)}
function spawnShouter(){if(featuredShouter&&featuredShouter.event)return;featuredShouter=P.find(p=>!p.event&&p!==featuredHat)||P[5];featuredShouter.featured='shouter';featuredShouter.anger=90;featuredShouter.x=790;featuredShouter.y=390;const target=freePeople(1,p=>p!==featuredShouter&&p.group!==featuredShouter.group)[0];if(!target)return;createEvent('fight',[featuredShouter,target],815,410,18);toast('ظهر شيء جديد في الساحة')}
function eventTargets(p,e){const r=p.role;if(e.type==='hat')return {x:e.x,y:e.y,mood:'happy',state:'hat'};if(e.type==='friends')return {x:e.x+(r?-28:28),y:e.y,mood:'happy',state:'friends'};if(e.type==='help')return {x:e.x+(r?-36:36),y:e.y+(r?7:-2),mood:r?'tired':'happy',state:r?'receive':'help'};if(e.type==='fight')return {x:e.x+(r?-42:42),y:e.y,mood:'angry',state:'fight'};if(e.type==='prank')return {x:e.x+(r?-44:44),y:e.y,mood:r?'fear':'happy',state:r?'startled':'prank'};if(e.type==='panic')return {x:e.x+(r?-26:26),y:e.y+(r?18:-8),mood:'fear',state:'panic'};if(e.type==='pose')return {x:e.x,y:e.y,mood:'happy',state:'pose'};return {x:p.tx,y:p.ty,mood:'calm',state:'walk'}}
function separation(p){let sx=0,sy=0;for(const q of P){if(q===p)continue;let dx=p.x-q.x,dy=p.y-q.y,d2=dx*dx+dy*dy;if(d2>0&&d2<1600){let d=Math.sqrt(d2),f=(40-d)/40;sx+=dx/d*f*34;sy+=dy/d*f*22}}return {x:sx,y:sy}}
function steer(p,tx,ty,speed,dt){let dx=tx-p.x,dy=ty-p.y,d=Math.hypot(dx,dy)||1;let sep=separation(p);let dvx=dx/d*speed+sep.x,dvy=dy/d*speed+sep.y;let a=expBlend(5.8,dt);p.vx+=(dvx-p.vx)*a;p.vy+=(dvy-p.vy)*a;p.x+=p.vx*dt;p.y+=p.vy*dt;p.face=Math.abs(p.vx)>1?Math.sign(p.vx):p.face}
function applyPostWatch(p){if(!p.action)return;if(p.action==='panic'){p.actionT=rand(2.2,4);p.state='panicRun';p.tx=p.group?65:W-65;p.ty=rand(320,620)}else if(p.action==='mimic'){p.actionT=rand(2.5,4.2);p.state='mimic'}else if(p.action==='pose'){p.actionT=rand(2.8,4.8);p.state='poseFree'}else if(p.action==='help'){p.actionT=rand(2,3.5);p.state='warm'}p.action=''}
function updatePerson(p,dt){p.cooldown=Math.max(0,p.cooldown-dt);p.reactionT=Math.max(0,p.reactionT-dt);if(p.watchT>0){p.watchT-=dt;p.face=1;p.vx*=Math.exp(-9*dt);p.vy*=Math.exp(-9*dt);p.state='watch';if(p.watchT<=0)applyPostWatch(p);return}if(p.event){const t=eventTargets(p,p.event);p.mood=t.mood;p.state=t.state;steer(p,t.x,t.y,p.event.type==='panic'?72:47,dt)}else if(p.actionT>0){p.actionT-=dt;if(p.state==='panicRun'){p.mood='fear';steer(p,p.tx,p.ty,92+Math.min(35,p.fear*.25),dt)}else if(p.state==='mimic'){p.mood='happy';p.vx*=Math.exp(-5*dt);p.vy*=Math.exp(-5*dt)}else if(p.state==='poseFree'){p.mood='happy';p.face=Math.sign(lens.x-p.x)||1;p.vx*=Math.exp(-7*dt);p.vy*=Math.exp(-7*dt)}else{p.mood='happy';steer(p,p.tx,p.ty,30,dt)}if(p.actionT<=0){p.state='walk';p.mood='calm';p.tx=rand(55,W-55);p.ty=rand(305,H-58)}}else{if(p.cooldown<=0&&(p.vanity>55||p.fame>35)&&Math.abs(p.x-lens.x)<210&&Math.abs(p.y-lens.y)<140&&Math.random()<dt*.5){p.state='poseFree';p.actionT=rand(1.5,2.7);p.mood='happy';return}let dx=p.tx-p.x,dy=p.ty-p.y,d=Math.hypot(dx,dy);if(d<22||Math.random()<dt*.035){p.tx=rand(55,W-55);p.ty=rand(305,H-58)}p.mood=p.fear>65?'fear':p.anger>70?'angry':'calm';p.state='walk';steer(p,p.tx,p.ty,p.speed*(p.fear>70?1.28:1),dt)}p.x=clamp(p.x,38,W-38);p.y=clamp(p.y,292,H-48);p.phase+=Math.hypot(p.vx,p.vy)*dt*.085}
let spawnTimer=3.8;function dynamicEncounters(dt){if(G.phase<2)return;for(let i=0;i<P.length;i++)for(let j=i+1;j<P.length;j++){const a=P[i],b=P[j];if(a.event||b.event||a.cooldown>0||b.cooldown>0||a.group===b.group)continue;const d=Math.hypot(a.x-b.x,a.y-b.y);if(d>48)continue;let hostility=(a.anger+b.anger+G.anger+G.division*.7)/300;if(Math.random()<dt*hostility*.085){createEvent('fight',[a,b],(a.x+b.x)/2,(a.y+b.y)/2,rand(6,9));a.cooldown=b.cooldown=7;return}}}
function updateEvents(dt){for(let i=E.length-1;i>=0;i--){const e=E[i];e.t+=dt;if(e.t>e.life)releaseEvent(e)}}
function chooseSpawn(){let pool=['help','friends'];if(G.phase>=1)pool.push('prank');if(G.phase>=2)pool.push('fight');if(G.phase>=3)pool.push('panic','prank','fight');if(G.vanity>42)pool.push('pose','prank');if(G.anger>46)pool.push('fight','fight');if(G.fear>46)pool.push('panic','panic');return pick(pool)}
function updateBroadcast(dt){const b=G.broadcast;if(!b||!b.active)return;b.t+=dt;b.waveX-=b.speed*dt;for(const p of P){if(p.seenToken===b.token||!b.targets.has(p.id))continue;if(p.x>=b.waveX){p.seenToken=b.token;triggerReaction(p,b.effect)}}if(b.waveX<-55){b.active=false;setTimeout(()=>afterBroadcast(b.effect),250)}}
function simulate(dt){if(!G.run||G.pause)return;G.time+=dt;updateBroadcast(dt);updateEvents(dt);P.forEach(p=>updatePerson(p,dt));dynamicEncounters(dt);spawnTimer-=dt;if(spawnTimer<=0){spawnTimer=rand(3.7,6);if(E.length<4)spawnEvent(chooseSpawn())}if(G.interesting>=2&&G.phase<2){G.phase=2;spawnShouter()}if((G.anger>30||G.fear>28)&&G.phase<3){G.phase=3;setPhase('المدينة بدأت تتعلم من الشاشة')}if((G.anger>58||G.fear>58||G.vanity>62)&&G.phase<4){G.phase=4;setPhase('الصور أصبحت تصنع الأحداث')}if(!G.end&&(G.anger>88||G.fear>88||G.vanity>90||G.shots>=20&&G.phase>=3))setTimeout(finish,500);updateHUD()}
function rr(g,x,y,w,h,r){g.beginPath();g.roundRect(x,y,w,h,r)}function limb(g,x1,y1,cx,cy,x2,y2){g.beginPath();g.moveTo(x1,y1);g.quadraticCurveTo(cx,cy,x2,y2);g.stroke()}
function drawPerson(g,p,photo=false){const walking=p.state==='walk'||p.state==='panicRun';const step=walking?Math.sin(p.phase):0;const speed=Math.hypot(p.vx,p.vy);const bob=walking?Math.abs(Math.sin(p.phase*2))*1.8:0;const jump=(p.state==='mimic'||p.state==='prank')?Math.max(0,Math.sin(p.phase*2.4))*8:0;g.save();g.translate(p.x,p.y+bob-jump);g.scale(p.face||1,1);g.strokeStyle='#252a27';g.lineWidth=3;g.lineCap='round';g.lineJoin='round';const legAmp=clamp(speed/55,0,1)*9;limb(g,-6,25,-8,36,-9+step*legAmp,48);limb(g,6,25,8,36,9-step*legAmp,48);g.fillStyle=p.color;rr(g,-14,-3,28,37,10);g.fill();g.stroke();g.fillStyle=p.group?'#426e89':'#b24f47';g.fillRect(-14,20,28,6);let la=[-12,5,-20,14,-22,27],ra=[12,5,20,14,22,27];if(p.state==='fight'){la=[-12,3,-27,-7,-34,-17];ra=[12,3,27,-3,35,-8]}if(p.state==='help'){ra=[12,4,28,10,38,12]}if(p.state==='receive'){la=[-12,4,-28,10,-38,12]}if(['prank','startled','panic'].includes(p.state)){la=[-12,3,-28,-6,-35,-18];ra=[12,3,28,-6,35,-18]}if(['pose','poseFree','mimic'].includes(p.state)){la=[-12,4,-27,-6,-34,-18];ra=[12,4,27,2,34,-7]}if(p.state==='watch'){la=[-12,5,-18,12,-15,22];ra=[12,5,18,12,15,22]}limb(g,...la);limb(g,...ra);g.fillStyle=p.skin;if(p.group){rr(g,-18,-38,36,36,7);g.fill();g.stroke()}else{g.beginPath();g.arc(0,-20,18,0,TAU);g.fill();g.stroke()}if(p.hat||p.fancyHat){g.fillStyle=p.fancyHat?'#e4af3f':'#d7a64a';g.beginPath();g.moveTo(-22,-38);g.lineTo(0,p.fancyHat?-64:-57);g.lineTo(22,-38);g.closePath();g.fill();g.stroke();if(p.fancyHat){g.fillStyle='#c6594e';g.fillRect(-6,-48,12,5)}}g.fillStyle='#242826';g.beginPath();g.arc(-6,-21,2,0,TAU);g.arc(6,-21,2,0,TAU);g.fill();g.beginPath();if(p.mood==='happy')g.arc(0,-14,6,.15*Math.PI,.85*Math.PI);else if(p.mood==='fear')g.arc(0,-14,3,0,TAU);else{g.moveTo(-3,-14);g.lineTo(3,-14)}g.stroke();if(p.mood==='angry'){g.beginPath();g.moveTo(-11,-29);g.lineTo(-3,-25);g.moveTo(11,-29);g.lineTo(3,-25);g.stroke()}if(p.reactionT>0&&!photo){const k=1+Math.sin((1.5-p.reactionT)*10)*.08;g.scale(k,k);g.fillStyle='#f6efe1';g.strokeStyle='#252a27';g.lineWidth=2;rr(g,-17,-72,34,25,9);g.fill();g.stroke();g.fillStyle=reactionColor(p.reaction);g.font='900 15px Tahoma';g.textAlign='center';g.fillText(reactionGlyph(p.reaction),0,-54);g.textAlign='start'}g.restore()}
function reactionGlyph(t){return t==='hat'?'▲':t==='anger'?'!':t==='fear'?'؟':t==='vanity'?'★':t==='kind'?'♥':t==='unity'?'↔':'•'}function reactionColor(t){return t==='anger'?'#d85549':t==='fear'?'#657ca4':t==='vanity'?'#d69b3f':t==='kind'||t==='unity'?'#5e9273':'#d6a84c'}
function drawEventDetails(g,e){if(e.type==='friends'){g.fillStyle='#d85a55';g.font='900 18px Tahoma';g.textAlign='center';g.fillText('♥',e.x,e.y-62);g.textAlign='start'}if(e.type==='help'){g.fillStyle='#8a603c';g.fillRect(e.x-2,e.y+18,9,6)}if(e.type==='fight'){g.strokeStyle='#d4554a';g.lineWidth=3;for(let i=0;i<3;i++){g.beginPath();g.moveTo(e.x-5+i*6,e.y-70-i*3);g.lineTo(e.x+2+i*6,e.y-81-i*3);g.stroke()}}if(e.type==='prank'){g.fillStyle='#d99b3f';g.font='900 18px Tahoma';g.fillText('★',e.x-6,e.y-66)}if(e.type==='panic'){g.strokeStyle='#637b9b';g.lineWidth=2;g.beginPath();g.arc(e.x,e.y-52,20,Math.PI*1.1,Math.PI*1.9);g.stroke()}}
function drawWorld(g,photo=false){g.fillStyle='#dce5df';g.fillRect(0,0,W,H);const B=[[0,82,150,160],[160,48,150,194],[320,95,125,147],[455,44,175,198],[642,78,138,164],[792,52,160,190],[962,88,115,154]];B.forEach((b,i)=>{g.fillStyle=i%2?'#b8aa93':'#c7baa2';g.fillRect(...b);g.fillStyle='#52605a';for(let x=b[0]+17;x<b[0]+b[2]-8;x+=31)for(let y=b[1]+22;y<b[1]+b[3]-8;y+=36)g.fillRect(x,y,12,14)});g.fillStyle='#8d918e';g.fillRect(0,215,W,68);g.strokeStyle='#eee4d2';g.lineWidth=4;g.setLineDash([28,25]);g.beginPath();g.moveTo(0,248);g.lineTo(W,248);g.stroke();g.setLineDash([]);g.fillStyle='#cbc3b3';g.fillRect(0,283,W,H-283);g.strokeStyle='#aaa292';g.lineWidth=1;g.globalAlpha=.28;for(let y=304;y<H;y+=42){g.beginPath();g.moveTo(0,y);g.lineTo(W,y);g.stroke()}for(let x=18;x<W;x+=68){g.beginPath();g.moveTo(x,283);g.lineTo(x,H);g.stroke()}g.globalAlpha=1;g.fillStyle='#9db487';rr(g,26,340,190,210,22);g.fill();rr(g,855,500,155,142,22);g.fill();[[55,380],[160,418],[92,486],[900,540],[963,594]].forEach(([x,y])=>{g.fillStyle='#715c43';g.fillRect(x-4,y,8,24);g.fillStyle='#62825b';g.beginPath();g.arc(x,y,20,0,TAU);g.fill()});g.fillStyle='#a25f4e';rr(g,805,330,180,96,8);g.fill();g.fillStyle='#efd28a';g.fillRect(818,348,154,21);g.fillStyle='#303632';g.font='900 15px Tahoma';g.textAlign='center';g.fillText('مقهى',895,364);g.textAlign='start';g.fillStyle='#7e9391';g.beginPath();g.ellipse(540,485,92,36,0,0,TAU);g.fill();g.fillStyle='#b9d0ce';g.beginPath();g.ellipse(540,478,73,24,0,0,TAU);g.fill();g.fillStyle='#765d45';g.fillRect(280,390,82,8);g.fillRect(288,398,6,15);g.fillRect(348,398,6,15);E.forEach(e=>drawEventDetails(g,e));[...P].sort((a,b)=>a.y-b.y).forEach(p=>drawPerson(g,p,photo));if(!photo){drawBroadcastWave(g);drawLens(g)}}
function drawLens(g){let x=lens.x-lens.w/2,y=lens.y-lens.h/2;g.fillStyle='#0b0e0c29';g.fillRect(0,0,W,y);g.fillRect(0,y,x,lens.h);g.fillRect(x+lens.w,y,W-x-lens.w,lens.h);g.fillRect(0,y+lens.h,W,H-y-lens.h);g.strokeStyle='#f7f1e7';g.lineWidth=3;g.setLineDash([10,7]);rr(g,x,y,lens.w,lens.h,12);g.stroke();g.setLineDash([]);g.strokeStyle='#202522';g.lineWidth=6;const n=24;[[x,y,1,1],[x+lens.w,y,-1,1],[x,y+lens.h,1,-1],[x+lens.w,y+lens.h,-1,-1]].forEach(([a,b,sx,sy])=>{g.beginPath();g.moveTo(a,b+sy*n);g.lineTo(a,b);g.lineTo(a+sx*n,b);g.stroke()})}
function drawBroadcastWave(g){const b=G.broadcast;if(!b||!b.active)return;let x=b.waveX;let grd=g.createLinearGradient(x-45,0,x+45,0);grd.addColorStop(0,'#f0c25d00');grd.addColorStop(.5,`rgba(240,194,93,${.1+.18*b.reach})`);grd.addColorStop(1,'#f0c25d00');g.fillStyle=grd;g.fillRect(x-45,283,90,H-283);g.strokeStyle=`rgba(244,210,130,${.28+.38*b.reach})`;g.lineWidth=2;g.beginPath();g.moveTo(x,292);g.lineTo(x,H-22);g.stroke()}
function resize(){const r=C.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);C.width=Math.max(1,Math.round(r.width*d));C.height=Math.max(1,Math.round(r.height*d));const s=Math.max(C.width/W,C.height/H),ox=(C.width-W*s)/2,oy=(C.height-H*s)/2;X.setTransform(s,0,0,s,ox,oy);C.map={s,ox,oy}}
function canvasPos(e){const r=C.getBoundingClientRect(),m=C.map,px=(e.clientX-r.left)*(C.width/r.width),py=(e.clientY-r.top)*(C.height/r.height);return{x:(px-m.ox)/m.s,y:(py-m.oy)/m.s}}
function moveLens(e){if(!G.run||G.pause)return;const p=canvasPos(e);lens.x=clamp(p.x,lens.w/2+4,W-lens.w/2-4);lens.y=clamp(p.y,lens.h/2+4,H-lens.h/2-5);$('tip').style.opacity='0'}
C.addEventListener('pointerdown',e=>{lens.drag=true;lens.moved=false;lens.downX=e.clientX;lens.downY=e.clientY;C.setPointerCapture?.(e.pointerId);moveLens(e)});C.addEventListener('pointermove',e=>{if(!lens.drag)return;if(Math.hypot(e.clientX-lens.downX,e.clientY-lens.downY)>6)lens.moved=true;moveLens(e)});C.addEventListener('pointerup',()=>{lens.drag=false});C.addEventListener('pointercancel',()=>lens.drag=false);
function subjects(){return P.filter(p=>Math.abs(p.x-lens.x)<lens.w*.47&&Math.abs(p.y-lens.y)<lens.h*.44)}
function analyze(){const ss=subjects();if(!ss.length)return {kind:'empty',ss};let best=null;for(const e of E){const inside=e.people.filter(p=>ss.includes(p));if(!inside.length)continue;const score=inside.length*12-Math.hypot(e.x-lens.x,e.y-lens.y)/90;if(!best||score>best.score)best={e,inside,score}}if(best){let composition=best.inside.length===best.e.people.length?(ss.length>=4?'crowd':'full'):'single'+best.inside[0].role;return {kind:best.e.type,ss,e:best.e,inside:best.inside,composition}}const fancy=ss.find(p=>p.fancyHat);if(fancy)return {kind:'hat',ss,e:null,inside:[fancy],composition:'full'};const hatted=ss.find(p=>p.hat&&!p.fancyHat);if(hatted)return {kind:'hatFollower',ss,e:null,inside:[hatted],composition:'full'};const poser=ss.find(p=>p.state==='poseFree'||p.vanity>60&&Math.abs(p.x-lens.x)<80);if(poser)return {kind:'pose',ss,e:null,inside:[poser],composition:ss.length>2?'crowd':'full'};return {kind:'ordinary',ss,composition:ss.length===1?'single':'group'}}
function makeStory(a){const z={caption:'يوم عادي. لا شيء تغيّر.',reach:.06,effect:{type:'none',power:0},impact:'الصورة مرّت دون أن تلفت أحداً.'};if(a.kind==='empty')return z;const single=a.composition.startsWith('single'),role=single?Number(a.composition.slice(-1)):-1,crowd=a.composition==='crowd';if(a.kind==='hat'){z.caption='قبعة غريبة تلفت أنظار المدينة.';z.reach=.78;z.effect={type:'hatTrend',power:1};z.impact='بعد ثوانٍ، تبدأ القبعة بالظهور على رؤوس أخرى.'}else if(a.kind==='hatFollower'){z.caption='القبعة التي كانت غريبة أصبحت في كل مكان.';z.reach=.72;z.effect={type:'hatBored',power:1};z.impact='ما كان مميزاً قبل لحظة صار عادياً… والناس يتركونه.'}else if(a.kind==='help'){if(single){z.caption=role===0?'شخص ينحني نحو شيء خارج الصورة.':'شخص يبدو عاجزاً وسط الساحة.';z.reach=.33;z.effect={type:'uncertainty',power:.35};z.impact='قلة من الناس فهمت ما حدث، والبقية رأت لحظة ناقصة.'}else{z.caption='شخص يتوقف لمساعدة غريب.';z.reach=.27;z.effect={type:'kindness',power:.65};z.impact='عدد قليل يقلد المساعدة؛ الصورة الهادئة لا تنتشر بعيداً.'}}else if(a.kind==='friends'){z.caption='شخصان من جماعتين مختلفتين يضحكان معاً.';z.reach=G.division>35?.32:.17;z.effect={type:'unity',power:.55};z.impact='البعض يبتسم… لكن معظم المدينة لا تعطي الصورة اهتماماً.'}else if(a.kind==='fight'){const aggressor=a.e.people[0],target=a.e.people[1];if(single){const shown=a.inside[0];z.caption='غاضب يصرخ… والسبب خارج الصورة.';z.reach=.91;z.effect={type:'croppedAnger',power:1,shownGroup:shown.group,otherGroup:shown.group?0:1};z.impact='الجماعة الأخرى ترى تهديداً. بعضهم يتراجع، وبعضهم يستعد للرد.'}else if(crowd){z.caption='الجمهور يبتعد عن مشادة في الساحة.';z.reach=.97;z.effect={type:'massFear',power:1.08,groups:[aggressor.group,target.group]};z.impact='الخوف ينتشر أسرع من تفاصيل الخلاف؛ يبدأ أشخاص بعيدون بالهرب.'}else{z.caption='مشادة بين شخصين من جماعتين مختلفتين.';z.reach=.94;z.effect={type:'division',power:1};z.impact='كل جماعة تتذكر شكل الأخرى داخل صورة الغضب. المواجهات تصبح أسهل.'}}else if(a.kind==='prank'){if(single&&role===1){z.caption='شخص مذعور… ولا يظهر سبب ذعره.';z.reach=.88;z.effect={type:'fear',power:.9};z.impact='الخوف ينتشر بلا سبب واضح؛ آخرون يبدأون بالتلفت والهرب.'}else{z.caption=single?'شخص يستعرض وحده أمام الكاميرا.':'مقلب يجذب أنظار المارة.';z.reach=.86;z.effect={type:'vanity',power:1};z.impact='الانتباه مكافأة. شخصيات أخرى تبدأ بتقليد الحركة والبحث عن الكاميرا.'}}else if(a.kind==='panic'){z.caption=single?'شخص يهرب… من ماذا؟':'الذعر ينتقل من شخص إلى آخر.';z.reach=.98;z.effect={type:'massFear',power:1.15};z.impact='حتى من لم ير الحدث يرى الهروب؛ الخوف أصبح حدثاً بحد ذاته.'}else if(a.kind==='pose'){z.caption='شخص يعرف تماماً أين توجد الكاميرا.';z.reach=.84;z.effect={type:'vanity',power:1.1};z.impact='الظهور نفسه أصبح سلوكاً قابلاً للتقليد.'}else if(a.kind==='ordinary'){z.caption=a.ss.length>3?'مجموعة تمضي في يوم عادي.':'لا شيء مثير هنا.';z.reach=.05;z.effect={type:'none',power:0};z.impact='لم يهتم الجمهور. المدينة واصلت ما كانت تفعله.'}return z}
function snapshot(){const sx=lens.x-lens.w/2,sy=lens.y-lens.h/2,sc=Math.max(SHOT.width/lens.w,SHOT.height/lens.h);SX.save();SX.clearRect(0,0,SHOT.width,SHOT.height);SX.setTransform(sc,0,0,sc,-sx*sc,-sy*sc);drawWorld(SX,true);SX.restore()}
function effectTargets(effect,reach){const ids=new Set();for(const p of P){let chance=reach;if(effect.type==='croppedAnger'){chance*=p.group===effect.otherGroup?1:.78}if(effect.type==='kindness'||effect.type==='unity')chance*=.85;if(Math.random()<chance)ids.add(p.id)}return ids}
function triggerReaction(p,e){p.watchT=rand(.30,.62);p.reactionT=1.55;if(e.type==='hatTrend'){p.reaction='hat';if(Math.random()<.74&&!p.fancyHat)p.hat=true;p.vanity+=5}else if(e.type==='hatBored'){p.reaction='hat';if(!p.fancyHat)p.hat=false;p.vanity=Math.max(0,p.vanity-2)}else if(e.type==='croppedAnger'){if(p.group===e.otherGroup){p.reaction=Math.random()<.52?'fear':'anger';p.fear+=rand(10,18);p.anger+=rand(7,15);if(p.reaction==='fear'&&Math.random()<.45)p.action='panic'}else{p.reaction='anger';p.anger+=rand(5,11)}}else if(e.type==='division'){p.reaction='anger';p.anger+=rand(9,17);p.fear+=rand(2,7)}else if(e.type==='fear'||e.type==='massFear'){p.reaction='fear';p.fear+=rand(12,23)*e.power;if(Math.random()<.55)p.action='panic'}else if(e.type==='vanity'){p.reaction='vanity';p.vanity+=rand(15,25)*e.power;p.fame+=rand(2,5);if(Math.random()<.5)p.action='mimic';else if(Math.random()<.45)p.action='pose'}else if(e.type==='kindness'){p.reaction='kind';p.empathy+=rand(5,11);p.anger=Math.max(0,p.anger-rand(2,6));if(Math.random()<.28)p.action='help'}else if(e.type==='unity'){p.reaction='unity';p.anger=Math.max(0,p.anger-rand(3,7));p.fear=Math.max(0,p.fear-rand(2,5));p.empathy+=4}else if(e.type==='uncertainty'){p.reaction='fear';p.fear+=rand(1,5)}else{p.reaction='none'}p.anger=clamp(p.anger,0,100);p.fear=clamp(p.fear,0,100);p.vanity=clamp(p.vanity,0,100);p.empathy=clamp(p.empathy,0,100)}
function applyGlobal(e){const k=e.power||1;if(e.type==='hatTrend'){G.hatTrend=1;G.vanity=clamp(G.vanity+9,0,100);G.phase=Math.max(G.phase,1);G.interesting++}if(e.type==='hatBored'){G.hatBored=1;G.vanity=clamp(G.vanity-4,0,100);G.interesting++;G.phase=Math.max(G.phase,2)}if(e.type==='croppedAnger'){G.anger=clamp(G.anger+14*k,0,100);G.fear=clamp(G.fear+10*k,0,100);G.division=clamp(G.division+12*k,0,100);G.trust-=6;G.interesting++}if(e.type==='division'){G.anger=clamp(G.anger+15*k,0,100);G.fear=clamp(G.fear+6*k,0,100);G.division=clamp(G.division+17*k,0,100);G.trust-=5;G.interesting++}if(e.type==='fear'||e.type==='massFear'){G.fear=clamp(G.fear+18*k,0,100);G.anger=clamp(G.anger+4*k,0,100);G.trust-=5;G.interesting++}if(e.type==='vanity'){G.vanity=clamp(G.vanity+19*k,0,100);G.trust-=2;G.interesting++}if(e.type==='kindness'){G.trust=clamp(G.trust+5*k,0,100);G.anger=clamp(G.anger-5*k,0,100);G.fear=clamp(G.fear-3*k,0,100)}if(e.type==='unity'){G.trust=clamp(G.trust+4*k,0,100);G.division=clamp(G.division-7*k,0,100);G.anger=clamp(G.anger-4*k,0,100)}G.trust=clamp(G.trust,0,100)}
function beginBroadcast(a,z){G.broadcastToken++;const reach=clamp(z.reach,0,1);G.broadcast={token:G.broadcastToken,effect:z.effect,reach,targets:effectTargets(z.effect,reach),waveX:W+45,speed:760,active:true,t:0};applyGlobal(z.effect);$('broadcast').classList.add('live');$('caption').textContent=z.caption;$('effect').textContent=z.impact;$('reachFill').style.width=Math.round(reach*100)+'%';$('reachText').textContent=Math.round(reach*100)+'% من المدينة';setTimeout(()=>{if(G.broadcast&&G.broadcast.token===G.broadcastToken)$('broadcast').classList.remove('live')},3200)}
function afterBroadcast(e){if(e.type==='hatTrend'){setTimeout(()=>{if(G.run&&!G.pause)toast('انظر إلى رؤوس الناس…')},300)}else if(e.type==='hatBored'){setTimeout(()=>{if(G.run&&!G.pause)spawnShouter()},600)}else if(e.type==='croppedAnger'||e.type==='division'){setTimeout(()=>spawnEvent('fight'),500);setTimeout(()=>spawnEvent('fight'),1700)}else if(e.type==='fear'||e.type==='massFear'){setTimeout(()=>spawnEvent('panic'),500);setTimeout(()=>spawnEvent('panic'),1600)}else if(e.type==='vanity'){setTimeout(()=>spawnEvent('prank'),600);setTimeout(()=>spawnEvent('pose'),1500)}else if(e.type==='kindness'){setTimeout(()=>spawnEvent('help'),900)}else if(e.type==='unity'){setTimeout(()=>spawnEvent('friends'),900)}}
function capture(){if(!G.run||G.pause)return;const a=analyze();if(a.kind==='empty')return toast('لا أحد داخل الكادر');const z=makeStory(a);G.shots++;if(z.reach>.2)G.interesting++;snapshot();$('signal').style.display='none';flash();shutterSound();beginBroadcast(a,z);toast(z.reach>.8?'الصورة تنتشر بسرعة':'تم البث — راقب الناس');if(a.e&&a.kind!=='hat')a.e.people.forEach(p=>p.fame=clamp(p.fame+z.reach*18,0,100));if(G.shots===1)$('tip').textContent='الآن راقب رد الفعل قبل الصورة التالية'}
function setPhase(t){$('phaseTag').textContent=t}function updateHUD(){$('fear').textContent=Math.round(G.fear);$('anger').textContent=Math.round(G.anger);$('vanity').textContent=Math.round(G.vanity);let t='مدينة هادئة';if(G.phase===1)t='موضة جديدة';if(G.phase===2)t='شيء يتغير';if(G.phase===3)t='التوتر ينتشر';if(G.phase>=4)t='الصور تصنع الأحداث';if(G.fear>72)t='مدينة خائفة';if(G.anger>72)t='مدينة غاضبة';if(G.vanity>76)t='الجميع يريد الظهور';$('phaseTag').textContent=t}
function toast(t){const e=$('toast');e.textContent=t;e.classList.add('on');clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.classList.remove('on'),1500)}function flash(){const e=$('flash');e.classList.remove('on');void e.offsetWidth;e.classList.add('on')}
let AC=null;function shutterSound(){try{AC=AC||new(window.AudioContext||window.webkitAudioContext)();const o=AC.createOscillator(),g=AC.createGain();o.type='triangle';o.frequency.setValueAtTime(230,AC.currentTime);o.frequency.exponentialRampToValueAtTime(520,AC.currentTime+.035);g.gain.setValueAtTime(.055,AC.currentTime);g.gain.exponentialRampToValueAtTime(.001,AC.currentTime+.11);o.connect(g);g.connect(AC.destination);o.start();o.stop(AC.currentTime+.12)}catch(e){}}
function finish(){if(G.end)return;G.end=true;G.run=false;G.pause=true;let title,text;if(G.anger>=G.fear&&G.anger>=G.vanity){title='الغضب تعلّم كيف يظهر';text='في البداية صوّرت حدثاً. في النهاية صار الناس يصنعون الحدث لأن الغضب هو ما تعلّموا أن الشاشة تكافئه.'}else if(G.fear>=G.vanity){title='الخوف أصبح أسرع من الحقيقة';text='لم يعد أحد يحتاج إلى رؤية سبب الهروب. رؤية الآخرين وهم خائفون أصبحت سبباً كافياً لخوف جديد.'}else{title='المدينة تؤدي أمامك';text='كلما كافأت الشاشة الاستعراض، تعلّم أشخاص أكثر أن يتصرفوا من أجل الكادر لا من أجل بعضهم.'}$('endTitle').textContent=title;$('endText').textContent=text;document.querySelectorAll('.modal').forEach(m=>m.classList.remove('on'));$('ending').classList.add('on')}
$('start').onclick=()=>{document.querySelectorAll('.modal').forEach(m=>m.classList.remove('on'));G.run=true;G.pause=false;spawnInitial();toast('ابدأ بما يلفت نظرك')};$('shutter').onclick=capture;$('help').onclick=()=>{G.pause=true;$('helpModal').classList.add('on')};$('closeHelp').onclick=()=>{$('helpModal').classList.remove('on');G.pause=false};addEventListener('resize',resize);addEventListener('orientationchange',()=>setTimeout(resize,120));resize();updateHUD();let last=performance.now(),acc=0;const STEP=1/60;function frame(now){let dt=Math.min(.08,(now-last)/1000);last=now;acc+=dt;let n=0;while(acc>=STEP&&n<5){simulate(STEP);acc-=STEP;n++}X.clearRect(0,0,W,H);drawWorld(X,false);requestAnimationFrame(frame)}requestAnimationFrame(frame);
})();