(()=>{'use strict';
const $=id=>document.getElementById(id),C=$('game'),X=C.getContext('2d'),P=$('photo'),PX=P.getContext('2d'),W=1280,H=720,T=Math.PI*2;
const R=(a,b)=>a+Math.random()*(b-a),K=(v,a,b)=>Math.max(a,Math.min(b,v)),Q=a=>a[(Math.random()*a.length)|0],F=n=>Math.round(n).toLocaleString('ar-EG');
const S={run:false,pause:true,time:150,posts:0,followers:1240,trust:62,tension:24,hype:18,trend:'الحياة اليومية',latest:'',aggr:.12,kind:.2,attention:.15,mission:0,best:0,combo:0,end:false};
const L={x:640,y:390,z:1,drag:false,levels:[{w:250,h:165,n:'قريب'},{w:350,h:225,n:'متوسط'},{w:475,h:290,n:'واسع'}]};
const names=['سلمى','عمر','ليان','مالك','نور','آدم','مريم','يونس','رهف','سامي','آية','كريم','لينا','أنس','هبة','زياد','جود','ريان','سارة','علي','ريم','مازن','هالة','إياد'],cols=['#d9685b','#d79a45','#5d9b81','#6686bd','#9173ad','#c47d9a','#829461','#b97452'],skins=['#f0d0a8','#d8ab7e','#a96f4d','#7a4a35'],acc=['cap','glasses','hair','phone','scarf','none','beanie','bag'];
const D={argument:{n:'مشادة في الساحة',c:'#d65449',d:11,icon:'!'},wallet:{n:'محفظة ضائعة',c:'#d49a3f',d:12,icon:'▣'},kindness:{n:'مساعدة عابر',c:'#5d8e70',d:11,icon:'♥'},prank:{n:'مقلب للفت الانتباه',c:'#bd7841',d:10,icon:'★'},artist:{n:'عرض شارع',c:'#77669e',d:13,icon:'♪'},selfie:{n:'بحث عن الشهرة',c:'#5d82a7',d:10,icon:'●'}};
const M=['التقط حدثًا يظهر فيه شخصان على الأقل','انشر قصة بسياق واضح أكثر من 75%','اصنع منشورًا يتجاوز 20 ألف مشاهدة','التقط لقطة واسعة تضم جمهورًا وحدثًا','حافظ على الثقة بعد المنشور القادم'];
const people=[],events=[],fx=[],bubbles=[];
function person(i){return{id:i,name:names[i],x:R(80,1200),y:R(240,620),tx:R(80,1200),ty:R(240,620),vx:0,vy:0,spd:R(35,60),col:cols[i%cols.length],skin:skins[i%skins.length],acc:acc[i%acc.length],bob:R(0,T),face:1,event:null,role:0,state:'walk',mood:'calm',fame:R(0,8),rep:0,att:R(.05,.25),held:null}}
for(let i=0;i<24;i++)people.push(person(i));
function free(n){return people.filter(p=>!p.event).sort(()=>Math.random()-.5).slice(0,n)}
function spawn(type){if(events.length>3)return;type=type||Q(Object.keys(D));let ar=free(type==='artist'?3:2);if(ar.length<(type==='artist'?3:2))return;let e={type,ar,x:R(270,1030),y:R(290,555),t:0};events.push(e);ar.forEach((p,i)=>{p.event=e;p.role=i;p.state='event';p.tx=e.x+(i-0.5)*72;p.ty=e.y})}
function clearE(e){e.ar.forEach(p=>{p.event=null;p.state='walk';p.mood='calm';p.held=null;p.tx=R(80,1200);p.ty=R(240,620)});events.splice(events.indexOf(e),1)}
function pose(p,e,dt){let i=p.role;p.face=i? -1:1;if(e.type==='argument'){p.tx=e.x+(i?-48:48);p.mood='angry';p.state='argue'}if(e.type==='wallet'){p.tx=e.x+(i?45:-45);p.mood=i?'surprise':'focus';p.state=i?'reach':'offer';p.held=i?null:'wallet'}if(e.type==='kindness'){p.tx=e.x+(i?38:-38);p.mood=i?'tired':'happy';p.state=i?'receive':'help'}if(e.type==='prank'){p.tx=e.x+(i?46:-46);p.mood=i?'surprise':'hype';p.state=i?'startled':'prank'}if(e.type==='artist'){p.tx=e.x+(i===0?0:i===1?-75:75);p.mood='happy';p.state=i===0?'dance':'watch';p.held=i===0?'music':null}if(e.type==='selfie'){p.tx=e.x+(i?24:-24);p.mood='happy';p.state='pose';p.held=i?'phone':null}p.ty=e.y+(e.type==='artist'&&i?28:0);p.x+=(p.tx-p.x)*Math.min(1,dt*4);p.y+=(p.ty-p.y)*Math.min(1,dt*4)}
function updP(p,dt){p.bob+=dt*(4+p.spd/70);if(p.event)return pose(p,p.event,dt);let near=Math.abs(p.x-L.x)<220&&Math.abs(p.y-L.y)<150;if((p.fame>22||p.att>.55)&&near&&Math.random()<dt*.55){p.state='pose';p.mood='hype';p.face=Math.sign(L.x-p.x)||1;return}p.state=p.rep<-20?'sad':'walk';p.mood=p.rep<-20?'sad':'calm';let dx=p.tx-p.x,dy=p.ty-p.y,d=Math.hypot(dx,dy);if(d<18||Math.random()<dt*.07){p.tx=R(70,1210);p.ty=R(225,625);dx=p.tx-p.x;dy=p.ty-p.y;d=Math.hypot(dx,dy)}d=Math.max(1,d);let sp=p.spd*(p.state==='sad'?.55:1);p.vx+=(dx/d*sp-p.vx)*dt*2;p.vy+=(dy/d*sp*.7-p.vy)*dt*2;p.x+=p.vx*dt;p.y+=p.vy*dt;p.face=Math.sign(p.vx)||p.face}
let spT=1.5;function update(dt){if(!S.run||S.pause)return;S.time-=dt;if(S.time<=0)return end();spT-=dt;if(spT<=0){spT=R(3.8,6.2);let r=Math.random(),type=r<S.aggr?'argument':r<S.aggr+S.kind?'kindness':r<.52?'wallet':r<.72?'prank':r<.87?'artist':'selfie';spawn(type)}for(let i=events.length-1;i>=0;i--){events[i].t+=dt;if(events[i].t>D[events[i].type].d)clearE(events[i])}people.forEach(p=>updP(p,dt));for(let i=fx.length-1;i>=0;i--){let f=fx[i];f.life-=dt;f.y+=f.vy*dt;f.vy+=30*dt;if(f.life<=0)fx.splice(i,1)}for(let i=bubbles.length-1;i>=0;i--){if((bubbles[i].life-=dt)<=0)bubbles.splice(i,1)}ui()}
function rr(g,x,y,w,h,r){g.beginPath();g.roundRect(x,y,w,h,r)}function limb(g,a,b,c,d,e,f){g.beginPath();g.moveTo(a,b);g.quadraticCurveTo(c,d,e,f);g.stroke()}
function drawP(g,p,photo=false){let walk=p.state==='walk'?Math.sin(p.bob):0,bob=p.state==='walk'?Math.abs(walk)*2:Math.sin(p.bob)*.7,jump=p.state==='dance'||p.state==='prank'?Math.max(0,Math.sin(p.bob*2))*7:0;g.save();g.translate(p.x,p.y+bob-jump);g.scale(p.face,1);g.strokeStyle='#252a27';g.lineWidth=3;g.lineCap='round';limb(g,-7,24,-9,35,-10+walk*8,47);limb(g,7,24,9,35,10-walk*8,47);g.fillStyle=p.col;rr(g,-14,-3,28,35,10);g.fill();g.stroke();let a=[-12,5,-21,15,-18,27],b=[12,5,21,15,18,27];if(p.state==='argue'){a=[-12,4,-26,-4,-34,-15];b=[12,4,27,0,35,-5]}if(['offer','help'].includes(p.state))b=[12,4,27,8,37,11];if(['reach','receive'].includes(p.state))a=[-12,4,-27,8,-37,11];if(p.state==='prank'||p.state==='startled'){a=[-12,4,-28,-5,-35,-18];b=[12,4,28,-5,35,-18]}if(p.state==='dance'){a=[-12,4,-27,-9,-34,-20];b=[12,4,27,6,34,18]}if(p.state==='pose'){a=[-12,4,-26,-6,-32,-18];b=[12,4,24,0,31,-7]}limb(g,...a);limb(g,...b);g.fillStyle=p.skin;g.beginPath();g.arc(0,-20,18,0,T);g.fill();g.stroke();if(p.acc==='hair'){g.fillStyle='#44372f';g.beginPath();g.arc(0,-29,14,Math.PI,T);g.fill()}if(p.acc==='cap'||p.acc==='beanie'){g.fillStyle=p.acc==='cap'?'#405872':'#695e86';g.beginPath();g.arc(0,-30,14,Math.PI,T);g.fill();g.fillRect(-13,-30,26,4)}g.fillStyle='#242927';g.beginPath();g.arc(-6,-21,2,0,T);g.arc(6,-21,2,0,T);g.fill();g.beginPath();if(['happy','hype'].includes(p.mood))g.arc(0,-14,6,.15*Math.PI,.85*Math.PI);else if(['sad','tired'].includes(p.mood))g.arc(0,-9,5,1.15*Math.PI,1.85*Math.PI);else if(p.mood==='surprise')g.arc(0,-14,3,0,T);else{g.moveTo(-3,-14);g.lineTo(3,-14)}g.stroke();if(p.mood==='angry'){g.beginPath();g.moveTo(-11,-28);g.lineTo(-3,-25);g.moveTo(11,-28);g.lineTo(3,-25);g.stroke()}if(p.acc==='glasses'){g.strokeRect(-13,-26,10,8);g.strokeRect(3,-26,10,8)}if(p.acc==='scarf'){g.fillStyle='#d0a34b';g.fillRect(-13,-2,26,5)}if(p.acc==='bag'){g.fillStyle='#654d3f';g.fillRect(-21,8,8,18)}if(p.held==='wallet'){g.fillStyle='#865938';g.fillRect(30,8,11,8)}if(p.held==='phone'||p.acc==='phone'&&p.state==='pose'){g.fillStyle='#303837';g.fillRect(27,-14,7,13)}if(p.held==='music'){g.fillStyle='#3f4140';g.beginPath();g.arc(29,5,8,0,T);g.fill()}if(!photo&&p.fame>25){g.fillStyle='#efb849';g.font='900 13px Tahoma';g.fillText('★',18,-42)}if(!photo&&p.rep<-20){g.fillStyle='#d9544b';g.font='900 13px Tahoma';g.fillText('!',18,-42)}g.restore()}
function world(g,photo=false){g.fillStyle='#d8e2dc';g.fillRect(0,0,W,H);let bs=[[0,80,170,150],[180,45,180,185],[370,92,130,138],[510,40,190,190],[710,78,150,152],[870,50,180,180],[1060,85,220,145]];bs.forEach((b,i)=>{g.fillStyle=i%2?'#b8a78e':'#c7b99f';g.fillRect(...b);g.fillStyle='#536059';for(let x=b[0]+18;x<b[0]+b[2]-10;x+=35)for(let y=b[1]+22;y<b[1]+b[3]-10;y+=38)g.fillRect(x,y,14,16)});g.fillStyle='#8d918e';g.fillRect(0,205,W,70);g.strokeStyle='#eee2c8';g.lineWidth=4;g.setLineDash([28,28]);g.beginPath();g.moveTo(0,240);g.lineTo(W,240);g.stroke();g.setLineDash([]);g.fillStyle='#c9c1b1';g.fillRect(0,275,W,H-275);g.strokeStyle='#aaa292';g.globalAlpha=.35;for(let y=295;y<H;y+=42){g.beginPath();g.moveTo(0,y);g.lineTo(W,y);g.stroke()}for(let x=0;x<W;x+=72){g.beginPath();g.moveTo(x,275);g.lineTo(x,H);g.stroke()}g.globalAlpha=1;g.fillStyle='#9fb58a';rr(g,35,320,215,225,24);g.fill();[[72,365],[185,405],[110,480],[1160,350],[1100,525]].forEach(([x,y])=>{g.fillStyle='#705b43';g.fillRect(x-4,y,8,26);g.fillStyle='#5f8259';g.beginPath();g.arc(x,y,22,0,T);g.fill()});g.fillStyle='#9e5d4d';rr(g,995,325,205,105,8);g.fill();g.fillStyle='#efd38a';g.fillRect(1010,343,175,24);g.fillStyle='#2e3431';g.font='900 18px Tahoma';g.textAlign='center';g.fillText('مقهى',1097,362);g.textAlign='start';g.fillStyle='#8a9f9b';g.beginPath();g.ellipse(640,470,110,42,0,0,T);g.fill();g.fillStyle='#bdd4d2';g.beginPath();g.ellipse(640,462,88,30,0,0,T);g.fill();g.fillStyle='#657e87';rr(g,315,360,120,88,8);g.fill();g.fillStyle='#e6d2a8';g.fillRect(326,373,98,18);g.fillStyle='#28302d';g.font='700 13px Tahoma';g.fillText('صحف',367,387);if(!photo)events.forEach(e=>{g.globalAlpha=.09;g.fillStyle=D[e.type].c;g.beginPath();g.ellipse(e.x,e.y+28,78,27,0,0,T);g.fill();g.globalAlpha=1});[...people].sort((a,b)=>a.y-b.y).forEach(p=>drawP(g,p,photo));fx.forEach(f=>{g.globalAlpha=K(f.life,0,1);g.fillStyle=f.c;g.font='900 18px Tahoma';g.fillText(f.ch,f.x,f.y)});g.globalAlpha=1;if(!photo){bubbles.forEach(b=>bubbleDraw(g,b));lensDraw(g)}}
function bubbleDraw(g,b){let x=b.p.x,y=b.p.y-72;g.font='700 10px Tahoma';let w=Math.max(55,g.measureText(b.t).width+18);g.globalAlpha=K(b.life,0,1);g.fillStyle=b.c;rr(g,x-w/2,y-22,w,25,9);g.fill();g.fillStyle='#fff';g.textAlign='center';g.fillText(b.t,x,y-6);g.textAlign='start';g.globalAlpha=1}
function lensDraw(g){let z=L.levels[L.z],x=L.x-z.w/2,y=L.y-z.h/2;g.fillStyle='#0c100e28';g.fillRect(0,0,W,y);g.fillRect(0,y,x,z.h);g.fillRect(x+z.w,y,W-x-z.w,z.h);g.fillRect(0,y+z.h,W,H-y-z.h);g.strokeStyle='#f5eee2';g.lineWidth=3;g.setLineDash([12,8]);rr(g,x,y,z.w,z.h,13);g.stroke();g.setLineDash([]);g.strokeStyle='#202522';g.lineWidth=7;let n=28;[[x,y,1,1],[x+z.w,y,-1,1],[x,y+z.h,1,-1],[x+z.w,y+z.h,-1,-1]].forEach(([a,b,c,d])=>{g.beginPath();g.moveTo(a,b+d*n);g.lineTo(a,b);g.lineTo(a+c*n,b);g.stroke()})}
function resize(){let r=C.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);C.width=Math.round(r.width*d);C.height=Math.round(r.height*d);let sc=Math.max(C.width/W,C.height/H),ox=(C.width-W*sc)/2,oy=(C.height-H*sc)/2;X.setTransform(sc,0,0,sc,ox,oy);C.map={sc,ox,oy}}
function pos(e){let r=C.getBoundingClientRect(),m=C.map,px=(e.clientX-r.left)*(C.width/r.width),py=(e.clientY-r.top)*(C.height/r.height);return{x:(px-m.ox)/m.sc,y:(py-m.oy)/m.sc}}
function move(e){if(!S.run||S.pause)return;let p=pos(e),z=L.levels[L.z];L.x=K(p.x,z.w/2+5,W-z.w/2-5);L.y=K(p.y,z.h/2+115,H-z.h/2-82);inside()}
C.onpointerdown=e=>{L.drag=true;C.setPointerCapture?.(e.pointerId);move(e)};C.onpointermove=e=>L.drag&&move(e);C.onpointerup=C.onpointercancel=()=>L.drag=false;
function subs(){let z=L.levels[L.z];return people.filter(p=>Math.abs(p.x-L.x)<z.w*.47&&Math.abs(p.y-L.y)<z.h*.45)}function inside(){let n=subs().length;$('subjectCount').textContent=n===0?'لا أحد':n===1?'شخص واحد':n+' أشخاص'}
function zoom(v){if(S.pause)return;L.z=K(L.z+v,0,2);$('zoomLabel').textContent=L.levels[L.z].n;inside();beep()}
function analyze(){let ss=subs(),best=null;events.forEach(e=>{let ar=e.ar.filter(p=>ss.includes(p));if(ar.length){let sc=ar.length*10-Math.abs(e.x-L.x)/100;if(!best||sc>best.sc)best={e,ar,sc}}});if(!best)return{type:'ordinary',variant:ss.length>1?'group':'single',ss,truth:ss.length>1?75:70};let e=best.e,ar=best.ar,v='both',truth=92;if(ar.length<e.ar.length){v='single'+ar[0].role;truth=e.type==='wallet'?32:e.type==='argument'?38:e.type==='prank'?36:46}else if(ss.length>=4){v='crowd';truth=84}return{type:e.type,variant:v,ss,e,truth}}
function script(s){let full=s.variant==='both'||s.variant==='crowd',one=s.variant.startsWith('single'),role=one?+s.variant.slice(-1):-1,name=D[s.type]?.n||'لحظة عادية',label,title,summary;if(s.type==='ordinary'){label=s.variant==='group'?'مجموعة بلا حدث واضح':'لحظة عادية';title=s.variant==='group'?'مجموعة من المارة':'شخص يعبر الساحة';summary='لا يوجد حدث مؤكد. يمكنك ترك الصورة كما هي أو صناعة قصة من لحظة عادية.'}else if(full){label=s.variant==='crowd'?'الحدث والجمهور داخل الصورة':'السياق الرئيسي كامل';title=name;summary='الكادر يُظهر الأطراف الرئيسية، لذلك يستطيع المشاهد فهم الحدث بدرجة جيدة.'}else{label='طرف واحد فقط داخل الكادر';if(s.type==='wallet')title=role===0?'شخص يحمل محفظة ليست له':'شخص يبحث عن شيء فقده';else if(s.type==='argument')title='غضب بلا سبب ظاهر';else if(s.type==='kindness')title=role===0?'شخص ينحني نحو شيء خارج الصورة':'شخص يحتاج للمساعدة';else if(s.type==='prank')title=role===0?'شخص يحاول لفت الانتباه':'لحظة ذعر بلا سبب ظاهر';else title='جزء من القصة فقط';summary='حدود الكادر أخفت شخصًا مهمًا. نفس اللحظة قد تحمل معنى مختلفًا تمامًا.'}let positive=['kindness','wallet','artist'].includes(s.type),negative=['argument','prank'].includes(s.type);let truthful=full?(positive?'قصة كاملة كما حدثت':'ما حدث فعلاً أمام المارة'):'لقطة ناقصة السياق — لا نحكم عليها';let sensational=full?(negative?'الفوضى التي تتحدث عنها المدينة!':positive?'لن تصدق ما حدث هنا!':'الصورة التي ستشعل المدينة'):(s.type==='wallet'&&role===0?'لص في وضح النهار!':s.type==='argument'?'معتدٍ يرعب المارة بلا سبب!':s.type==='kindness'?'الجميع تجاهله!':s.type==='prank'?'لحظة رعب في قلب المدينة!':'سر غامض أمام الجميع!');let third=full?'من القصة… ومن الرواية؟':'ماذا حدث خارج حدود هذه الصورة؟';let truthEff=positive?[7,-5,-3]:negative?[4,-1,1]:[3,-1,-1],sensEff=positive?[0,2,10]:[-9,10,14],twEff=[-1,3,7];return{label,title,summary,truth:s.truth,choices:[[truthful,'صادق',...truthEff,full?14000:7000],[sensational,one?'مضلل':'مثير',...sensEff,one?43000:33000],[third,'ملتبس',...twEff,22000]]}}
function snap(){let z=L.levels[L.z],sx=L.x-z.w/2,sy=L.y-z.h/2,sc=Math.max(P.width/z.w,P.height/z.h);PX.save();PX.clearRect(0,0,P.width,P.height);PX.setTransform(sc,0,0,sc,-sx*sc,-sy*sc);world(PX,true);PX.restore()}
function capture(){if(!S.run||S.pause)return;if(!subs().length)return toast('الكادر فارغ… حرّكه نحو الناس');S.pause=true;flash();beep('shot');let s=analyze(),a=script(s);snap();$('compositionLabel').textContent=a.label;$('truthPercent').textContent=a.truth+'%';$('truthFill').style.width=a.truth+'%';$('truthFill').style.background=a.truth>74?'#5f8e70':a.truth>50?'#d99a39':'#d65449';$('storyTitle').textContent=a.title;$('storySummary').textContent=a.summary;let box=$('headlineOptions');box.innerHTML='';a.choices.forEach(ch=>{let b=document.createElement('button');b.className='headline';b.innerHTML=`<strong>${ch[0]}</strong><div class="meta"><span>${ch[1]}</span><span>وصول متوقع ${F(ch[6])}+</span></div>`;b.onclick=()=>publish(ch,s,a);box.appendChild(b)});modal('editor')}
function publish(ch,s,a){hide('editor');let old=S.trust,[head,tone,td,xd,hd,base]=ch,views=Math.round(base*R(.78,1.28)*(1+S.hype/160)),shares=Math.round(views*R(.04,.12)*(tone==='مثير'||tone==='مضلل'?1.5:1)),gain=Math.round(views/38);S.followers+=gain;S.trust=K(S.trust+td,0,100);S.tension=K(S.tension+xd,0,100);S.hype=K(S.hype+hd,0,100);S.posts++;S.latest=head;S.trend=D[s.type]?.n||'صورة غامضة';S.combo=(tone==='صادق'&&a.truth>70)||views>20000?S.combo+1:0;S.best=Math.max(S.best,S.combo);if(s.e)s.e.ar.forEach(p=>{p.fame=K(p.fame+views/1800,0,100);p.att=K(p.att+(hd>7?.14:.03),0,1);p.rep=K(p.rep+td*1.8,-100,100)});if(xd>5)S.aggr=K(S.aggr+.07,0,.6);if(td>5)S.kind=K(S.kind+.06,0,.7);if(hd>8)S.attention=K(S.attention+.08,0,.8);people.sort(()=>Math.random()-.5).slice(0,6).forEach((p,i)=>setTimeout(()=>bubble(p,td>5?Q(['قصة جميلة','هذا يعيد الثقة','أريد المزيد']):xd>5?Q(['المدينة لم تعد هادئة','رأيت الخبر!','ماذا يحدث؟']):Q(['هذا في كل مكان','أرسلوا الرابط','غريب…'])),i*180));setTimeout(()=>{if(S.run&&!S.pause)spawn(xd>5?'argument':td>5?'kindness':hd>8?'prank':null)},900);mission(s,a,views,old);viral(head,views,shares,gain,tone,s);ui()}
function bubble(p,t){bubbles.push({p,t,c:'#29302c',life:2.7})}function mission(s,a,v,old){let ok=S.mission===0?s.ss.length>=2:S.mission===1?a.truth>=75:S.mission===2?v>=20000:S.mission===3?s.ss.length>=4&&!!s.e:S.trust>=old;if(ok){S.followers+=500;toast('اكتملت المهمة +500 متابع');S.mission=(S.mission+1)%M.length}}
function viral(h,v,sh,g,tone,s){$('viralHeadline').textContent=h;$('viewsNum').textContent=F(v);$('sharesNum').textContent=F(sh);$('newFollowersNum').textContent=F(g);$('comments').innerHTML=(tone==='مضلل'?['الصورة واضحة جدًا!','انتظروا… أين بقية المشهد؟','هذه هي مدينتنا؟']:tone==='صادق'?['أخيرًا عنوان هادئ','السياق واضح','شكراً لعدم المبالغة']:['هذا في كل مكان','من هؤلاء؟','أريد القصة كاملة']).map((x,i)=>`<div class="comment"><span>@${names[(i*5+S.posts)%24]}</span>${x}</div>`).join('');$('consequence').textContent=tone==='مضلل'?'انتشرت الرواية أسرع من الحقيقة. بعض الشخصيات ستتصرف الآن بناءً على ما شاهدته، لا على ما حدث.':tone==='صادق'?'الثقة ارتفعت. السلوك الذي ظهر في الصورة أصبح أكثر قابلية للتقليد داخل المدينة.':'زاد الاهتمام بالحدث، ومعه رغبة بعض الشخصيات في الظهور أمام الكاميرا.';modal('viral')}
function end(){if(S.end)return;S.end=true;S.run=false;S.pause=true;let title,text;if(S.trust>=68&&S.tension<45){title='مدينة تصدّقك';text='كبر جمهورك من دون تحويل كل لحظة إلى أزمة. الناس ما زالوا يثقون بما تنشره.'}else if(S.hype>60&&S.trust<45){title='المدينة أمام الكاميرا';text='الكثير من الناس لم يعودوا يتصرفون لبعضهم، بل لكي تصوّرهم.'}else if(S.tension>65){title='مدينة على أعصابها';text='كل موقف صغير صار يبدو كأنه بداية كارثة. ما نشرته غيّر الشارع نفسه.'}else if(S.trust<35){title='لا أحد يعرف ماذا يصدق';text='الصور تنتشر، لكن الثقة اختفت. كل كادر ناقص أصبح حقيقة جديدة.'}else{title='جمهور أكبر… وأسئلة أكثر';text='اليوم انتهى، لكن أثر صورك بقي في الشخصيات والمدينة.'}$('endingTitle').textContent=title;$('endingText').textContent=text;$('endFollowers').textContent=F(S.followers);$('endTrust').textContent=Math.round(S.trust);$('endTension').textContent=Math.round(S.tension);$('endCombo').textContent=S.best;modal('endScreen')}
function ui(){$('trustStat').textContent=Math.round(S.trust);$('tensionStat').textContent=Math.round(S.tension);$('hypeStat').textContent=Math.round(S.hype);$('followersStat').textContent=F(S.followers);$('postCount').textContent=S.posts;$('trendText').textContent=S.trend;$('latestHeadline').textContent=S.latest?'— '+S.latest:'';let m=Math.max(0,S.time),mi=Math.floor(m/60),se=Math.floor(m%60);$('timer').textContent=String(mi).padStart(2,'0')+':'+String(se).padStart(2,'0');$('missionText').textContent=M[S.mission];$('missionBar').style.width='0%';inside();if(S.posts>=7&&!S.end)setTimeout(end,300)}
function modal(id){document.querySelectorAll('.modal').forEach(x=>x.classList.remove('show'));$(id).classList.add('show')}function hide(id){$(id).classList.remove('show')}function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(toast.x);toast.x=setTimeout(()=>$('toast').classList.remove('show'),1600)}function flash(){$('flash').classList.remove('go');void $('flash').offsetWidth;$('flash').classList.add('go')}let AC;function beep(k='ok'){try{AC=AC||new (window.AudioContext||window.webkitAudioContext)();let o=AC.createOscillator(),g=AC.createGain();o.frequency.value=k==='shot'?520:330;g.gain.setValueAtTime(.04,AC.currentTime);g.gain.exponentialRampToValueAtTime(.001,AC.currentTime+.12);o.connect(g);g.connect(AC.destination);o.start();o.stop(AC.currentTime+.13)}catch(e){}}
$('startBtn').onclick=()=>{hide('intro');S.run=true;S.pause=false;spawn('wallet');setTimeout(()=>spawn('argument'),1400);setTimeout(()=>spawn('kindness'),2900);toast('راقب الحدث ثم اختر حدود الصورة')};$('captureBtn').onclick=capture;$('zoomOut').onclick=()=>zoom(1);$('zoomIn').onclick=()=>zoom(-1);$('discardBtn').onclick=()=>{hide('editor');S.pause=false;S.trust=K(S.trust+1,0,100);toast('عدم النشر قرار أيضًا')};$('backCityBtn').onclick=()=>{hide('viral');if(S.posts>=7)return end();S.pause=false;toast('شاهد كيف تغيرت المدينة')};$('restartBtn').onclick=()=>location.reload();$('helpBtn').onclick=()=>{S.pause=true;modal('help')};$('closeHelp').onclick=()=>{hide('help');S.pause=!S.run};addEventListener('resize',resize);addEventListener('orientationchange',()=>setTimeout(resize,120));C.addEventListener('wheel',e=>{e.preventDefault();zoom(e.deltaY>0?1:-1)},{passive:false});
resize();ui();let last=performance.now();function loop(t){let dt=Math.min(.033,(t-last)/1000);last=t;update(dt);world(X);requestAnimationFrame(loop)}requestAnimationFrame(loop);
})();